### ISSUE TITLE
キュー実装

### ISSUE THREAD

**Issue by nirsmmy** [TeamKitten/Calf#1]
再生中の曲があった際にリクエストが来た場合、次に再生する曲としてキューを溜めるようにしたほうが使い勝手良さそう。

**Comment by TinyKitten** [comment]
お前がやれ

**Comment by TinyKitten** [comment]
https://github.com/TeamKitten/Calf/commit/af9d649a1655866a589db5fe6f08a0ccfff9f8e0
様子見

**Comment by TinyKitten** [comment]
問題なさそう
