### ISSUE TITLE
queueがそもそもただのnpだった

### ISSUE THREAD

**Issue by tearaikazuki** [TeamKitten/Calf#6]
何をどこでまちがえたか知らんが何もviewQueueとは言えない物だった🤔

**Comment by TinyKitten** [comment]
viewQueueじゃなくてqueueでは？

**Comment by tearaikazuki** [comment]
あっ

**Comment by TinyKitten** [comment]
間違いであればタイトルを変えてください。

**Comment by tearaikazuki** [comment]
はい

**Comment by TinyKitten** [comment]
https://github.com/TeamKitten/Calf/commit/93c118ffe824214e523f7c438da91178b94242aa

ここで修正済みのためClose
